/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View;

import Cotroller.ControleCurso;
import Model.Curso;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aluno
 */
public class FrmCurso extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmCurso
     */
    public FrmCurso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JtfIdCurso = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        JtfNomeCurso = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CbxStatusCurso = new javax.swing.JComboBox<>();
        JbCadastrarCurso = new javax.swing.JButton();
        JbAlterarCurso = new javax.swing.JButton();
        JbConsultarCurso = new javax.swing.JButton();
        JbDeletarCurso = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTableCurso = new javax.swing.JTable();
        JbCarregarCamposCurso = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("FORMULARIO DOS CURSOS");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("ID");

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("NOME CURSO");

        JtfNomeCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtfNomeCursoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("STATUS");

        CbxStatusCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONE", "NATIVO", "INATIVO" }));
        CbxStatusCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxStatusCursoActionPerformed(evt);
            }
        });

        JbCadastrarCurso.setText("CADASTRAR");
        JbCadastrarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbCadastrarCursoActionPerformed(evt);
            }
        });

        JbAlterarCurso.setText("ALTERAR");
        JbAlterarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbAlterarCursoActionPerformed(evt);
            }
        });

        JbConsultarCurso.setText("CONSULTAR");
        JbConsultarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbConsultarCursoActionPerformed(evt);
            }
        });

        JbDeletarCurso.setText("DELETAR");

        JTableCurso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "NOME", "STATUS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(JTableCurso);

        JbCarregarCamposCurso.setText("CARREGAR CAMPOS");
        JbCarregarCamposCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbCarregarCamposCursoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(237, 237, 237)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CbxStatusCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(176, 176, 176)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JtfIdCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JtfNomeCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(JbCadastrarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(JbAlterarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(JbConsultarCurso)
                                .addGap(18, 18, 18)
                                .addComponent(JbDeletarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(JbCarregarCamposCurso)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JtfIdCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(JtfNomeCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(CbxStatusCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JbAlterarCurso)
                    .addComponent(JbConsultarCurso)
                    .addComponent(JbDeletarCurso)
                    .addComponent(JbCadastrarCurso)
                    .addComponent(JbCarregarCamposCurso))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JtfNomeCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtfNomeCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtfNomeCursoActionPerformed

    private void CbxStatusCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxStatusCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbxStatusCursoActionPerformed

    private void JbAlterarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbAlterarCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JbAlterarCursoActionPerformed

    private void JbCarregarCamposCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbCarregarCamposCursoActionPerformed

    }//GEN-LAST:event_JbCarregarCamposCursoActionPerformed

    private void JbCadastrarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbCadastrarCursoActionPerformed
        cadastrarCursoView();
    }//GEN-LAST:event_JbCadastrarCursoActionPerformed

    private void JbConsultarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbConsultarCursoActionPerformed
        listarCursoView();
    }//GEN-LAST:event_JbConsultarCursoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbxStatusCurso;
    private javax.swing.JTable JTableCurso;
    private javax.swing.JButton JbAlterarCurso;
    private javax.swing.JButton JbCadastrarCurso;
    private javax.swing.JButton JbCarregarCamposCurso;
    private javax.swing.JButton JbConsultarCurso;
    private javax.swing.JButton JbDeletarCurso;
    private javax.swing.JTextField JtfIdCurso;
    private javax.swing.JTextField JtfNomeCurso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void cadastrarCursoView() {

        Curso objCurso = new Curso();
        objCurso.setNomeCurso(JtfNomeCurso.getText());
        objCurso.setStatusCurso((String) CbxStatusCurso.getSelectedItem());

        if (JtfNomeCurso.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Os campos não podem retornar vazios");
        } else {
            ControleCurso objControleCurso = new ControleCurso();
            objControleCurso.cadastrarCurso(objCurso);
            JOptionPane.showMessageDialog(null, "Curso cadastrado com sucesso");
        }
    }
    
    private void listarCursoView(){
        try {
            ControleCurso objControleCurso = new ControleCurso ();
            //usar tabela para exibir valores
            //geetModel para montar o modelo de tabela curso
            DefaultTableModel model = (DefaultTableModel)JTableCurso.getModel();
            model.setNumRows(0);
            
            ArrayList<Curso> lista = objControleCurso.consultarCurso();
            for (int num = 0; num < lista.size(); num++){
            model.addRow(new Object[]{
            lista.get(num).getIdCurso(),
            lista.get(num).getNomeCurso(),
            lista.get(num).getStatusCurso(),
            });
}
        } catch (Exception erro) {
           JOptionPane.showMessageDialog(null, "Lista Curso View FrmCurso" + erro); 
        }
    }
}



